baseURL = "https://databrickslabs.github.io/delta-oms/"
title = "Delta Operational Metrics Store (DeltaOMS)"
theme= "hugo-theme-learn"

pluralizeListTitles = false
canonifyURLs = true

[params]
    description = "DeltaOMS Documentation"
    author = "Himanish Kushary (Databricks)"
    disableShortcutsTitle = true
    disableLandingPageButton = false