baseURL = 'https://databrickslabs.github.io/delta-oms/'
languageCode = 'en-us'
title = 'Delta Operational Metrics Store (DeltaOMS)'
theme= 'hugo-theme-learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    description = 'DeltaOMS Documentation'
    author = 'Himanish Kushary (Databricks)'
    disableLandingPageButton = true
